# -*- coding: utf-8 -*-
"""ContactosMexicanos10digitosVCF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jBKqpP4-Oa_xVtDE1gyQDV8U3KJPY4QO

# Contactos Mexicanos 10 digitos version simple de escritorio
---

Con los cambios actuales de las formas de marcacion en Mexico multiples usuarios se ven retrasados en la forma de marcar. Es por eso que se hace este trabajo sencillo. Con la esperanza de eventualmente segirlo trabajando de forma abierta para solucionar una problematica sensilla.

---
>Para mas información: http://www.ift.org.mx/comunicacion-y-medios/comunicados-ift/es/partir-del-3-de-agosto-mexico-tendra-una-nueva-forma-de-marcacion-telefonica-comunicado-342019-16-de
---
Para generar data dummy se utilizo el generador proporcionado por @corysimmons https://github.com/corysimmons/vcf-generator

## Se obtiene la data:
"""

archivoOriginal = open('sample_data/dummy-contacts.vcf')
contactos = [x for x in archivoOriginal.readlines()]

"""## Se modifica la data:"""

contactos = [x.replace('+521','') if x[:3]=='TEL' else x for x in contactos]
contactos = [x.replace('+52 1','') if x[:3]=='TEL' else x for x in contactos]

"""## Se Guarda la informacion"""

with open('directorioResultado.vcf','w') as archivoFinal:
  archivoFinal.writelines(contactos)